Repository prgrms-fe-devcourse/FEDC3_HIT_NAYOUNG, pull requests merged in 2023-01, with the labels that each got.

#5 Feature/axios 초기 설정
  package.json
  src/Api/api.ts
  src/App.tsx
  yarn.lock
Labels: ☀Feature

#11 라우팅 초기 세팅
  package.json
  src/App.tsx
  src/components/Home/index.tsx
  src/components/Test.tsx
  src/components/Test/index.tsx
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/ReviewDetail/index.tsx
  src/pages/ReviewList/index.tsx
  src/pages/Signup/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: ☀Feature

#19 회원가입 기능 구현
  package.json
  src/components/SignupForm/WarningLabel.tsx
  src/components/SignupForm/index.tsx
  src/pages/Signup/index.tsx
  yarn.lock
Labels: ☀Feature

#17 홈페이지 > 전자기기 카테고리 구현
  src/components/Home/Category/CategoryItem.tsx
  src/components/Home/Category/CategoryList.tsx
  src/types/index.d.ts
  yarn.lock
Labels: ☀Feature

#15 모달창(로그인/회원가입) 구현
  index.html
  package-lock.json
  src/App.tsx
  src/components/Home/index.tsx
  src/components/Modal/InformLoginModal.tsx
  src/components/Modal/ModalPortal.ts
  src/components/Modal/index.tsx
  src/components/Navigation/BottomNavigation.tsx
  src/components/Navigation/Logo.svg
  src/components/Navigation/NavigationItem.ts
  src/components/Navigation/SideNavigation.tsx
  src/components/Navigation/index.tsx
  src/components/Test/index.tsx
  src/main.tsx
  src/pages/Alarm/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyInformation/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/pages/Search/index.tsx
  src/pages/index.ts
  src/store/store.ts
  src/types/index.d.ts
  src/utils/constants.ts
  tailwind.config.cjs
  yarn.lock
Labels: ☀Feature

#20 리뷰 게시글 컴포넌트 기능 구현
  src/components/ReviewPoster/index.tsx
  src/pages/Home/index.tsx
  src/pages/ReviewDetail/index.tsx
Labels: ☀Feature

#21 로그인 구현 #8
  src/components/Login/Button.tsx
  src/components/Login/Input.tsx
  src/components/Login/Login.tsx
  src/pages/Login/index.tsx
Labels: ☀Feature

#29 홈페이지 > 메인 화면 Layout UI 구현
  src/components/Home/Category/CategoryItem.tsx
  src/components/Home/Category/CategoryList.tsx
  src/components/Home/ReviewPoster/index.tsx
  src/index.css
  src/pages/Home/index.tsx
  src/utils/constants.ts
Labels: ☀Feature, 💅Style

#30 유저 함수 구현 - 유저 인증, 유저 정보 받기
  src/Api/user.ts
Labels: ☀Feature

#33 홈페이지 > 메인 페이지 동시에 다중으로 API 통신 기능 구현
  src/Api/category.ts
  src/Api/reviewPoster.ts
  src/components/Home/Category/CategoryItem.tsx
  src/components/Home/Category/CategoryList.tsx
  src/components/Home/ReviewPoster/index.tsx
  src/components/ReviewList/ReviewCount.tsx
  src/components/ReviewList/ReviewListHeader.tsx
  src/components/ReviewList/ReviewListSection.tsx
  src/hooks/common/useResize.tsx
  src/index.css
  src/pages/Home/index.tsx
  src/pages/ReviewList/index.tsx
  src/types/index.d.ts
Labels: ☀Feature, 💅Style, 우선순위 높음

#35 뒤로가기 컴포넌트 구현
  src/components/common/BackNavigation.tsx
Labels: ☀Feature, 💅Style

#36 404 페이지 구현
  src/pages/NotFound/index.tsx
  tailwind.config.cjs
Labels: ☀Feature, 💅Style

#38 리뷰 생성 페이지 구현
  src/components/Home/ReviewPoster/index.tsx
  src/components/ReviewCreateForm/Button.tsx
  src/components/ReviewCreateForm/ErrorMessage.tsx
  src/components/ReviewCreateForm/RegisterInput.tsx
  src/components/ReviewCreateForm/RegisterTextarea.tsx
  src/components/ReviewCreateForm/index.tsx
  src/components/ReviewList/ReviewListSection.tsx
  src/index.css
  src/pages/ReviewCreate/index.tsx
  src/pages/ReviewList/index.tsx
  src/types/index.d.ts
Labels: ☀Feature, 우선순위 높음

#39 프로필, 프로필 편집 컴포넌트 구현
  .github/pull_request_template.md
  src/Api/user.ts
  src/App.tsx
  src/components/Profile/EditProfile.tsx
  src/components/Profile/index.tsx
  src/components/common/Avatar/index.tsx
  src/pages/EditMyProfile/index.tsx
  src/pages/MyInformation/index.tsx
  src/pages/index.ts
  src/types/index.d.ts
  src/utils/constants.ts
Labels: ☀Feature

#40 로그인, 회원가입 통일
  src/components/Auth/Login.tsx
  src/components/Auth/Logo.tsx
  src/components/Auth/SignUp.tsx
  src/components/Auth/WarningLabel.tsx
  src/components/Login/Logo.tsx
  src/index.css
  src/pages/Login/index.tsx
  src/pages/Signup/index.tsx
  tailwind.config.cjs
Labels: 🔨Refafactor, 💅Style

#41 리뷰 상세페이지 좋아요, 댓글 구현
  src/Api/comment.ts
  src/App.tsx
  src/components/Home/ReviewPoster/index.tsx
  src/components/Modal/InformLoginModal.tsx
  src/components/Navigation/BottomNavigation.tsx
  src/components/Navigation/NavigationItem.ts
  src/components/Navigation/SideNavigation.tsx
  src/components/ReviewComment/ReviewCommentInput.tsx
  src/components/ReviewComment/ReviewCommentList.tsx
  src/components/ReviewContent/index.tsx
  src/components/common/LikeButton.tsx
  src/index.css
  src/main.tsx
  src/pages/ReviewDetail/index.tsx
  src/store/store.ts
  src/types/index.d.ts
  src/utils/constants.ts
  src/utils/format.ts
Labels: ☀Feature, 🛠Fix, 💅Style

#43 회원가입 성공 시 토큰 저장
  src/components/Auth/SignUp.tsx
Labels: 🔨Refafactor

#45 리뷰 상세페이지 좋아요, 댓글 구현 리팩터링
  src/Api/comment.ts
  src/Api/user.ts
  src/components/Navigation/BottomNavigation.tsx
  src/components/Navigation/NavigationItem.ts
  src/components/Navigation/SideNavigation.tsx
  src/components/ReviewComment/Comment.tsx
  src/components/ReviewComment/ReviewCommentInput.tsx
  src/components/ReviewComment/ReviewCommentList.tsx
  src/types/index.d.ts
Labels: 🔨Refafactor

#53 리뷰 게시글에서 사용하는 카테고리 이름, id 전역 상태로 관리
  src/pages/Home/index.tsx
  src/store/recoilCategoryState.ts
Labels: ☀Feature

#55 추천 리뷰 게시글에서 잘못된 URL 수정
  src/Api/reviewPoster.ts
  src/components/Home/ReviewPoster/index.tsx
  src/pages/Home/index.tsx
Labels: 🛠Fix, 🐛Bug

#56 상세 페이지 수정, 삭제 구현
  src/Api/reviewDetail.ts
  src/components/Modal/InformLoginModal.tsx
  src/components/ReviewComment/Comment.tsx
  src/components/ReviewContent/index.tsx
  src/components/ReviewDetail/ReviewComment/ReviewCommentInput.tsx
  src/components/ReviewDetail/ReviewComment/ReviewCommentList.tsx
  src/components/ReviewDetail/ReviewContent/Button.tsx
  src/components/ReviewDetail/ReviewContent/ContentHandler.tsx
  src/components/ReviewDetail/ReviewContent/index.tsx
  src/components/common/BreadCrumbLinks/index.tsx
  src/components/common/LikeButton/index.tsx
  src/pages/Home/index.tsx
  src/pages/ReviewDetail/index.tsx
  src/store/recoilCommentState.ts
  src/store/recoilLikeState.ts
  src/store/recoilModalState.ts
  src/store/recoilReviewDetailState.ts
  src/store/store.ts
  src/types/index.d.ts
  src/utils/constants.ts
Labels: ☀Feature, 🔨Refactor

#58 리뷰작성 페이지 수정사항 반영
  src/components/ReviewCreateForm/InformCancelModal.tsx
  src/components/ReviewCreateForm/InformCreateLoadingModal.tsx
  src/components/ReviewCreateForm/RegisterInput.tsx
  src/components/ReviewCreateForm/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/store/recoilCategoryState.ts
  src/types/index.d.ts
Labels: ☀Feature, 우선순위 높음, 리뷰: 기능중점

#59 로그아웃 구현, 모달창 연결
  src/components/Modal/InformLogOutModal.tsx
  src/components/Modal/InformLoginModal.tsx
  src/components/Modal/index.tsx
  src/components/Navigation/BottomNavigation.tsx
  src/components/Navigation/SideNavigation.tsx
  src/components/Profile/index.tsx
  src/pages/Alarm/index.tsx
  src/pages/EditMyProfile/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyInformation/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/pages/ReviewDetail/index.tsx
  src/pages/ReviewList/index.tsx
  src/pages/Search/index.tsx
  src/store/store.ts
  src/types/index.d.ts
  src/utils/storage.ts
Labels: ☀Feature

#61 메인 페이지 리팩토링
  src/Api/category.ts
  src/Api/reviewPoster.ts
  src/components/Home/Category/CategorySection.tsx
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/components/Home/ReviewPoster/ReviewPosterSection.tsx
  src/components/ReviewList/ReviewListSection.tsx
  src/hooks/api/useFetchHIT.tsx
  src/pages/Home/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/store/recoilCategoryState.ts
  src/types/category.d.ts
  src/types/review.d.ts
  src/utils/constants.ts
Labels: 🔨Refactor

#62 좋아요, 댓글 생성 알림 전송
  src/Api/like.ts
  src/Api/notification.ts
  src/components/ReviewDetail/ReviewComment/Comment.tsx
  src/components/ReviewDetail/ReviewComment/ReviewCommentInput.tsx
  src/components/ReviewDetail/ReviewComment/ReviewCommentList.tsx
  src/components/ReviewDetail/ReviewContent/index.tsx
  src/components/common/LikeButton/index.tsx
  src/store/recoilLikeState.ts
  src/utils/constants.ts
Labels: ☀Feature

#67 카테고리 id,name 로컬스토리지로 관리
  src/Api/api.ts
  src/hooks/api/useFetchHIT.tsx
  src/pages/ReviewCreate/index.tsx
  src/store/recoilCategoryState.ts
  src/utils/category.ts
  src/utils/constants.ts
  src/utils/review.ts
  src/utils/storage.ts
Labels: 🛠Fix, 우선순위 높음

#66 프로필 페이지: 팔로우, 팔로우 취소, 게시글 조회
  src/Api/follow.ts
  src/Api/notification.ts
  src/Api/user.ts
  src/App.tsx
  src/components/Modal/InformUnfollowModal.tsx
  src/components/Profile/EditProfile.tsx
  src/components/Profile/EditProfileInput.tsx
  src/components/Profile/Figure.ts
  src/components/Profile/ReviewAndFollow.tsx
  src/components/Profile/ReviewItem.tsx
  src/components/Profile/ReviewList.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Profile/index.tsx
  src/components/common/Avatar/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserPage/index.tsx
  src/pages/index.ts
  src/store/recoilUserState.ts
  src/store/store.ts
  src/types/index.d.ts
Labels: ☀Feature

#68 알림 페이지 구현
  src/Api/alarm.ts
  src/components/Alarm/AlarmItem.tsx
  src/components/Alarm/NewAlarmList.tsx
  src/components/Alarm/ReadAlarmList.tsx
  src/components/Alarm/index.tsx
  src/hooks/api/useFetchHIT.tsx
  src/pages/Alarm/index.tsx
  src/store/Alarm/index.ts
  src/store/recoilCategoryState.ts
  src/types/index.d.ts
  src/utils/alarm.ts
  src/utils/category.ts
Labels: ☀Feature, 우선순위 높음

#71 사용자 목록 컴포넌트 구현
  src/Api/user.ts
  src/components/Home/UserList/UserItem.tsx
  src/components/Home/UserList/UserList.tsx
  src/pages/Home/index.tsx
  src/types/userList.d.ts
Labels: ☀Feature

#70 검색 페이지 UI 구현 & 검색 페이지 API 연결
  src/Api/reviewDetail.ts
  src/Api/search.ts
  src/components/Modal/InformUnfollowModal.tsx
  src/components/Profile/ReviewAndFollow.tsx
  src/components/Profile/ReviewItem.tsx
  src/components/Profile/ReviewList.tsx
  src/components/Profile/index.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchPostFeed.tsx
  src/components/Search/SearchTab.tsx
  src/components/Search/SearchUserFeed.tsx
  src/components/common/Avatar/index.tsx
  src/components/common/Feed/FeedItem.tsx
  src/components/common/Feed/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/LikeButton/index.tsx
  src/pages/Home/index.tsx
  src/pages/Search/index.tsx
  src/store/recoilSearchState.ts
  src/types/index.d.ts
  src/types/search.d.ts
  src/utils/constants.ts
Labels: ☀Feature

#79 모달창 버그 수정
  src/components/Navigation/SideNavigation/index.tsx
  src/components/Toast/index.tsx
  src/pages/Login/index.tsx
  src/pages/Search/index.tsx
  src/pages/Signup/index.tsx
Labels: 🛠Fix, 🐛Bug, 우선순위 높음

#82 Avatar컴포넌트 확장(팔로우 알림일 경우, 유저 이미지 보여주도록)
  src/components/Alarm/AlarmItem.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Profile/index.tsx
  src/components/common/Avatar/index.tsx
Labels: 💅Style

#80 기본 카테고리 노트북으로 변경 & 잘못된 카테고리 ID 수정
  src/Api/reviewPoster.ts
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/hooks/api/useFetchHIT.tsx
Labels: 🛠Fix, 🐛Bug

#83 수화 avatar 컴포넌트 수정 합치기 및 기본 프로필 이미지 추가
  src/assets/defaultProfileImage.png
  src/components/Home/UserList/UserItem.tsx
  src/components/common/Avatar/index.tsx
Labels: 🔨Refactor

#85 상수 변수 constants.ts로 이동
  src/Api/reviewPoster.ts
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/utils/constants.ts
Labels: 🔨Refactor

#86 alert를 Toast UI로 변경
  src/components/Profile/EditProfile.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Profile/index.tsx
  src/components/Toast/ToastText.ts
Labels: 🔨Refactor

#87 리뷰 게시글에서 불필요한 정보 숨기기
  src/Api/reviewPoster.ts
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/components/Home/ReviewPoster/ReviewPosterSection.tsx
  src/components/ReviewList/ReviewListSection.tsx
  src/hooks/api/useFetchHIT.tsx
  src/pages/ReviewList/index.tsx
  src/types/index.d.ts
  src/utils/review.ts
Labels: 🛠Fix

#88 전체 반응형 레이아웃 간격,너비 통일
  src/components/Alarm/index.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/SignUp.tsx
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/components/Modal/InformLogOutModal.tsx
  src/components/Modal/InformLoginModal.tsx
  src/components/Profile/EditProfile.tsx
  src/components/Profile/EditProfileInput.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Profile/index.tsx
  src/components/ReviewCreateForm/index.tsx
  src/components/ReviewDetail/ReviewContent/index.tsx
  src/components/ReviewUpdateForm/index.tsx
  src/index.css
  src/pages/Alarm/index.tsx
  src/pages/Home/index.tsx
  src/pages/ReviewCreate/index.tsx
  src/pages/ReviewDetail/index.tsx
  src/pages/ReviewUpdate/index.tsx
  src/pages/Search/index.tsx
Labels: 🔨Refactor, 💅Style

#89 사용자 목록 컴포넌트 수정사항 반영
  src/Api/user.ts
  src/components/Home/UserList/UserItem.tsx
  src/components/Home/UserList/UserList.tsx
Labels: ☀Feature, 💅Style, 우선순위 높음

#91 프로필 편집 input 에러 수정 및 label 추가
  src/components/Profile/EditProfile.tsx
  src/components/Profile/EditProfileInput.tsx
Labels: 🐛Bug

#92 프로필 리뷰 게시글 카테고리 로컬스토리지 연결
  src/components/Profile/ReviewList.tsx
Labels: 🛠Fix

#95 리뷰 게시글을 선택하면 로그인 유무에 따라 Modal 보여 주는 기능
  src/components/Home/ReviewPoster/ReviewPoster.tsx
  src/components/common/Feed/index.tsx
  src/hooks/api/useOpenAuthModal.tsx
Labels: ☀Feature

#96 카테고리별 리뷰 게시글에서 게시글이 존재하지 않으면 Not Found 화면 보여주기
  src/components/ReviewList/ReviewListSection.tsx
  src/pages/NotFound/index.tsx
Labels: ☀Feature

#99 검색 페이지 > 각 게시글 높이 통일 시키기
  src/components/common/Feed/FeedItem.tsx
Labels: 💅Style

#101 검색 페이지 > 마이 프로필 라우터 -> 유저 프로필 라우터로 변경
  src/components/Search/SearchUserFeed.tsx
Labels: 🛠Fix

#103 프로필 편집페이지 이미지 변경 Avatar 컴포넌트 적용
  src/components/Auth/Login.tsx
  src/components/Auth/SignUp.tsx
  src/components/Profile/EditProfile.tsx
  src/components/Profile/UserProfile.tsx
  src/components/Profile/index.tsx
  src/components/ReviewCreateForm/index.tsx
  src/components/ReviewDetail/ReviewContent/ContentHandler.tsx
  src/components/ReviewUpdateForm/index.tsx
Labels: 🔨Refactor

#104 로그인 엔터 버그 수정
  src/Api/user.ts
  src/components/Auth/Login.tsx
  src/components/Auth/SignUp.tsx
  src/components/ReviewCreateForm/index.tsx
  src/components/ReviewUpdateForm/index.tsx
Labels: 🛠Fix, 🐛Bug

#114 warning label 스타일 주입받도록 수정
  src/components/Auth/WarningLabel.tsx
Labels: 🔥 HurryUp 🔥

#108 React-hook-form 이용한 Input, textarea, 재사용가능한 컴포넌트로 확장(제네릭 활용)
  src/components/ReviewCreateForm/ErrorMessage.tsx
  src/components/ReviewCreateForm/RegisterInput.tsx
  src/components/ReviewCreateForm/RegisterTextarea.tsx
  src/components/ReviewCreateForm/index.tsx
  src/components/ReviewUpdateForm/index.tsx
  src/components/Search/SearchBar.tsx
  src/components/common/Input/index.tsx
  src/components/common/ReactHookForm/FormInput.tsx
  src/components/common/ReactHookForm/FormTextarea.tsx
  src/types/index.d.ts
Labels: 🔨Refactor

#117 회원가입 폼 특수문자 추가
  src/components/Auth/SignUp.tsx
  src/utils/constants.ts
  tailwind.config.cjs
Labels: 🐛 Bug, 🔥 HurryUp 🔥
